# 1. Introduction to Python: Exercise

Name: Carlos P.

In [2]:
import numpy as np

##  Lists and loops
Create the following lists, possibly in multiple ways.

1) odd positive integers below 20.

In [3]:
odd = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [4]:
odd = [n for n in range(1, 20) if n % 2 == 1]
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


2) sums from 1 to n, for up to n=10.

In [5]:
sums = []
for i in range(1, 11):
    n = 0
    while i > 0:
        n += i
        i -= 1
    sums.append(n)

print(sums)

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]


3) prime numbers below n=20.

In [6]:
primes = []
for n in range(2, 21):
    dividers = 0
    for d in range(2, n):
        if n % d == 0:
            dividers += 1
    if dividers == 0:
        primes.append(n)
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19]


4) n=10 random numbers between 0 and k=5.  
(use np.random.randint())

In [7]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [8]:
n = np.random.randint(0, 5, 10)
print(n)

[1 2 2 2 1 4 3 4 0 4]


5) from two lists of the same length, make a list with the larger of the items at the same position.

In [9]:
a = np.random.randint(10, size=5)
b = np.random.randint(10, size=5)
c = []
for i in range(5):
    if a[i] > b[i]:
        c.append(int(a[i]))
    else:
        c.append(int(b[i]))
print(a)
print(b)
print(c)


[3 4 4 6 9]
[7 3 5 8 7]
[7, 4, 5, 8, 9]


6) from a random list with 7 items, find the median 

In [10]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None, *, stable=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x7f5400b87e20>
File:            ~/Dev/Github/Oist/iSciComp/.venv/lib/python3.14/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and,
    in general, the actual implementation will vary with data type.
    The 'mergesort' option is retained for backwards compatibility.
order : str or list of str, optional
    When `a` is an array 

In [11]:
a = np.random.randint(0, 10, 7)
a_s = np.sort(a)
print(a_s)
print(a_s[3])

[0 0 1 3 6 6 9]
3


In [12]:
print(np.median(a))

3.0


## Arrays and matrices

1) an m-by-n matrix with random integers from 0 to k.

In [13]:
# for example
m=3
n=4
k=10
A = np.random.randint(0, k, (m, n))
print(A)

[[6 0 2 3]
 [9 7 5 8]
 [3 5 0 1]]


2) from a matrix, make a sub matrix of items in odd rows and even columns.

In [33]:
a = np.random.randint(0, 10, (5,5))
print(a)



print(a[::2, ::2])

[[4 6 6 0 1]
 [0 0 1 0 6]
 [0 0 5 9 8]
 [6 0 8 5 9]
 [8 2 6 1 5]]
[[4 6 1]
 [0 5 8]
 [8 6 5]]


3) make a m-by-n matrix with (i,j) component as i/j.

In [35]:
a = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        a[i, j] = (i+1) / (j+1)
print(a)

[[1.         0.5        0.33333333 0.25       0.2       ]
 [2.         1.         0.66666667 0.5        0.4       ]
 [3.         1.5        1.         0.75       0.6       ]
 [4.         2.         1.33333333 1.         0.8       ]
 [5.         2.5        1.66666667 1.25       1.        ]]


4) for a n-by-n matrix $A$, compute the k-th power $A^k$.

In [ ]:
a = np.random.randint(0, 10, (2,2))
k = 2
c = 1
print(a)

while c < k:
    a = a @ a
    c += 1

print(a)

[[9 4]
 [9 4]]
[[117  52]
 [117  52]]


In [41]:
print(np.linalg.matrix_power(a, k))

[[19773  8788]
 [19773  8788]]
