# 1. Introduction to Python

Python is a programming language developed in 1990s by Guido van Rossum.  
Its major features are:
- consice -- (relatively) easy to read
- extensible -- (so-called) object oriented
- free! -- unlike Matlab

It was originally used for "scripting" sequences of processing.  
Now it is widely used for scientific computing as well.

## Installing Python

Linux and Mac machines usually have Python pre-installed.  

To install and setup a variety of packages, it is easiest to install a curated distribution, such as:  
* Anaconda: https://www.anaconda.com/download

There is a free version of Anaconda for students and practitioners, but if you belong to an organization of more than 200 employees, a Business or Enterprise license is required (https://www.anaconda.com/pricing).

Anaconda also installs many packages you will never use.

To install python and packages without using Anaconda, refer to the section **Installing Python by Miniforge**.

## Starting Python

From a terminal, type
```
$ python  
```
to start a python interpreter.  

## Python as a calculator

At the python prompt `>>>`, try typing numbers and operators, like
```
>>> 1+1
```

In [71]:
1+1

2

In [72]:
2**8

256

In [73]:
# Uncomment (remove #) the line below
# exp(2)

The plain Python does not include math functions. You need to import numpy.

## Jupyter Notebook
For building a program step-by-step with notes and results attached, it is highly recommended to use a notebook interface, such as Jupyter Notebook (https://jupyter.org), which is included in Anaconda and other popular distributions.

To start Jupyter Notebook type in the terminal
```
$ jupyter notebook
```
which should open a web page showing your working directory.

You can create a new notebook from the New menu on the upper right corner, or open an existing .ipynb file like this.


### Working with the notebook
A notebook is made of "cells."  
You can make a new cell by "+" button on the Toolbar, or by typing ESC A (above) or ESC B (below).  
You can make a cell as Markdown (documentation) by ESC M, as Code by ESC Y, or simply by the Toolbar menu.  
You can delete a cell by ESC DD, or the Cut button on the Toolbar.  

### Markdown cell

Markdown is a simple text formatting tool, with

`#, ##, ###,...` for headings

`*, +, -,...` for bullets
* item 1
* item 2

`$  $` for Latex equations like $\sum_{i=1}^n \alpha_i$ in line

`$$  $$` for equations centered in a separate line

$$\sum_{i=1}^n \alpha_i$$

and two spaces at the end of the line  
for a line break.

See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for details.

You can format a Markdown cell by Shift+Return, and go back to Edit mode by Return

### Code cell
You can type Control+Return to run the cell or Shift+Return to run and move to the next cell.   
You can also use the triangle button or "Cell" menu to run cells.

In [74]:
2*3

6

## Integer and floating-point numbers
A number can be an *integer* or *floating-point*, which sometimes needs distinction.

In [75]:
type(1)

int

In [76]:
type(1.5)

float

In Python 3, division of integers can produce a float.  
In Python 2, it was truncated to an integer.

In [77]:
3 / 2  # 1.5 by Python 3; 1 by Python 2

1.5

You can perform integer division by `//` and get the remainder by `%`.

In [78]:
5 // 2

2

In [79]:
5 % 2

1

To make an integer as a floating point number, you can add `.`

In [80]:
type(1.)

float

## Variables
You can assing a number or result of computation to a variable.  

In [81]:
a = 1

In [82]:
a

1

In [83]:
b = a + a
b

2

Multiple variables can be assigned at once.

In [84]:
a, b = 3, 4
a

3

In [85]:
b

4

## Print function
You can check the content of a variable or an expression by typing it at the bottom of a cell.

You can use `print()` function to check the variables anywhere in a cell.
Multiple items listed by `,` are printed with a space in between.

A text string is represented by `' '` or `"  "`.

In [86]:
print(a, b)
print('a =', a)
print("a =", a, ' b =', b)

3 4
a = 3
a = 3  b = 4


You can use `.format()`, or simply a string starting with `f'` or `F'` to embed numbers in a text.

In [87]:
print('The weight is {0}g and the volume is {1}cc.'.format(a, b))

The weight is 3g and the volume is 4cc.


In [88]:
print(F'The weight is {a}g and the volume is {b}cc.')

The weight is 3g and the volume is 4cc.


You can specify the length by `:` for text, `:d` for integers, and `:f` for floating point numbers.  
A newline is started by `\n`.

In [89]:
print(F'weight {a} g\n{'volume':10}{b:6d} cc\n{'density':10}{a/b:6.3f} g/cc')

weight 3 g
volume         4 cc
density    0.750 g/cc


## Lists

You can create a list by surrounding items by [ ].

In [90]:
b = [1, 2, 3, 4]
b

[1, 2, 3, 4]

An item can be referenced by [ ], with index starting from 0. 

In [91]:
b[1]  # 2nd item

2

In [92]:
b[-1]  # last item

4

A colon can be used for indexing a part of list.

In [93]:
b[1:3]  # 2nd to 3rd

[2, 3]

In [94]:
b[:3]  # first to third

[1, 2, 3]

In [95]:
b[1:]  # 2nd to last

[2, 3, 4]

In [96]:
b[1::2]  # from 1st, step by 2

[2, 4]

In [97]:
b[::-1]  # all in reverse order

[4, 3, 2, 1]

For lists, + means concatenation

In [98]:
b + b

[1, 2, 3, 4, 1, 2, 3, 4]

You can create a nested list, like a matrix

In [99]:
A = [[1,2,3],[4,5,6]]
A

[[1, 2, 3], [4, 5, 6]]

An item in a nested list can be picked by [ ][ ], but not [ , ]

In [100]:
A[1]

[4, 5, 6]

In [101]:
A[1][2]

6

In [102]:
# A[1,2]  # this causes an error for a list

A list can contain different types of items with different lengths.

In [103]:
a = [1, 2, 3.14, 'apple', "orange", [1, 2]]
a

[1, 2, 3.14, 'apple', 'orange', [1, 2]]

When you assign a list to another list, only the pointer is copied.

In [104]:
a = [1, 2, 3]
b = a
b[1] = 4
a

[1, 4, 3]

When you want to copy the content, use [:]

In [105]:
a = [1, 2, 3]
b = a[:]
b[1] = 4
a

[1, 2, 3]

## Dictionary
When you store data as a list, you have to remember what you stored 1st, 2nd, ...

A dictionary allows you to access the value by name with `key:value` pairs.

In [106]:
# Postal codes in our neighborhood
postal = {'onna':9040411, 'tancha':9040412, 'fuchaku':9040413, 'oist':9040495}

You can check the value for a key by `[ ]`.

In [107]:
postal['oist']

9040495

## `if` branch
Branching by `if` statement looks like this. In Python, indentation specifies where a block of code starts and ends.

In [108]:
x = 1

In [109]:
if x>0:
    y = x
else:
    y = 0
y

1

There is a shorthand notation with the condition in the middle:

In [110]:
x if x>0 else 0

1

## `for` loop
A common way of `for` loop is by `range()` function.  
Don't forget a colon and indentation.

In [111]:
j = 0
for i in range(5):
    j = j + i
    print(i, j)

0 0
1 1
2 3
3 6
4 10


You can specify start, end and interval.

In [112]:
for i in range(3,9,2):
    print(i)

3
5
7


`for` loop can also be over a list.

In [113]:
a = [1, 2, 3]
for x in a:
    print(x**2)

1
4
9


In [114]:
s = "hello"
for c in s:  # characters in a string
    print(c)

h
e
l
l
o


In [115]:
s = ["hello", "goodby"]
for c in s:  # strings in a list
    print(c)

hello
goodby


`enumerate()` function gives pairs of index and content of a list.

In [116]:
for i, c in enumerate(s):
    print(i, c)

0 hello
1 goodby


You can also apply a for loop for a dictionary.

In [117]:
for k in postal: # get the key
    print('%8s:'%k, postal[k])

    onna: 9040411
  tancha: 9040412
 fuchaku: 9040413
    oist: 9040495


In [118]:
# get key-value pair
for (k, v) in postal.items():
    print('{0:8s}: {1}'.format(k, v))

onna    : 9040411
tancha  : 9040412
fuchaku : 9040413
oist    : 9040495


## List 'comprehension'
There is a quick way of constructing a list from a for loop.

In [119]:
y = [x**2 for x in range(5)]
y

[0, 1, 4, 9, 16]

## Numpy arrays
For most computation, you need to import `numpy` package by the following convention:

In [120]:
import numpy as np

Numpy `ndarray` is specialized for storing numbers of the same type.

In [121]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [122]:
type(b)

numpy.ndarray

In [123]:
type(b[0])

numpy.int64

Like a list, the index starts from zero

In [124]:
b[1]

np.int64(2)

Operators work component-wise.

In [125]:
b + b

array([2, 4, 6])

In [126]:
b * b

array([1, 4, 9])

In [127]:
b + 1  # broadcast

array([2, 3, 4])

`arange()` gives an evenly spaced array.

In [128]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

`linspace()` gives an array *including* the last point.

In [130]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [131]:
np.linspace(0, 10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Nested array
You can make a matrix as a nested array.

In [132]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

Components can be accessed by [ , ]

In [133]:
A[1][1]

np.int64(4)

In [134]:
A[1,0]  # this if fine for a numpy ndarray, not for a regular list

np.int64(3)

Take the first row

In [135]:
A[0]

array([1, 2])

In [136]:
A[0,:]

array([1, 2])

Take the second column

In [137]:
A[:,1]

array([2, 4])

Component-wise arithmetics

In [138]:
A + A

array([[2, 4],
       [6, 8]])

In [139]:
A * A

array([[ 1,  4],
       [ 9, 16]])

A matrix product is inner products of rows and columns, such as

$$\newcommand{\mat}[1]{\begin{pmatrix} #1 \end{pmatrix}}$$

$$ \mat{ a & b\\ c & d}\mat{ v & x\\ w & y} = \mat{ av+bw & ax+by\\ cv+dw & cx+dy}. $$

From Python 3.5, `@` symbol does the matrix product.

In [140]:
# matrix product
A @ A  # it should give [[1*1+2*3, 1*2+2*4], [3*1+4*3, 3*2+4*4]]

array([[ 7, 10],
       [15, 22]])

### Common matrices

In [141]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [143]:
np.empty([3,2])  # the contents are not specified

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [144]:
np.empty([3,2], dtype=int)   # to specify the data type

array([[0, 0],
       [0, 0],
       [0, 0]])

## Magic functions
In Jupyter notebook (or ipython), many *magic* functions preceded by `%` are available for working with the file system, etc.

In [145]:
# present working directory
%pwd

'/home/charly/Dev/Github/Oist/iSciComp'

You can use `%quickref` to see the list of magic functions

In [146]:
%quickref


IPython -- An enhanced Interactive Python - Quick Reference Card

obj?, obj??      : Get help, or more help for object (also works as
                   ?obj, ??obj).
?foo.*abc*       : List names in 'foo' containing 'abc' in them.
%magic           : Information about IPython's 'magic' % functions.

Magic functions are prefixed by % or %%, and typically take their arguments
without parentheses, quotes or even commas for convenience.  Line magics take a
single % and cell magics are prefixed with two %%.

Example magic function calls:

%alias d ls -F   : 'd' is now an alias for 'ls -F'
alias d ls -F    : Works if 'alias' not a python name
alist = %alias   : Get list of aliases to 'alist'
cd /usr/share    : Obvious. cd -<tab> to choose from visited dirs.
%cd??            : See help AND source for magic %cd
%timeit x=10     : time the 'x=10' statement with high precision.
%%timeit x=2**100
x**100           : time 'x**100' with a setup of 'x=2**100'; setup code is not
                   co

Or `%magic` for the full documentation.

In [166]:
%magic


IPython's 'magic' functions

The magic function system provides a series of functions which allow you to
control the behavior of IPython itself, plus a lot of system-type
features. There are two kinds of magics, line-oriented and cell-oriented.

Line magics are prefixed with the % character and work much like OS
command-line calls: they get as an argument the rest of the line, where
arguments are passed without parentheses or quotes.  For example, this will
time the given statement::

        %timeit range(1000)

Cell magics are prefixed with a double %%, and they are functions that get as
an argument not only the rest of the line, but also the lines below it in a
separate argument.  These magics are called with two arguments: the rest of the
call line and the body of the cell, consisting of the lines below the first.
For example::

        %%timeit x = numpy.random.randn((100, 100))
        numpy.linalg.svd(x)

will time the execution of the numpy svd routine, running the assignment 

You can also use `!` to run an OS command or a program.

In [148]:
!pwd

/home/charly/Dev/Github/Oist/iSciComp


In [167]:
!hostname

CharlyPC


## Saving and loading data
You can work with files by `open()`, `write()` and `read()` functions.

In [150]:
with open('haisai.txt', 'w') as f:
    f.write('Haisai!\n')
    f.write('Mensore!\n')
# f is closed when the `with` block is finished

In [151]:
%cat haisai.txt

Haisai!
Mensore!


In [152]:
with open('haisai.txt', 'r') as f:
    s = f.read()
print(s)

Haisai!
Mensore!



A common way of writing/reading a data file is to use `savetxt()` and `loadtxt()` functions of `numpy`.

In [153]:
X = [ [i, i**2] for i in range(5)]
X

[[0, 0], [1, 1], [2, 4], [3, 9], [4, 16]]

In [154]:
np.savetxt("square.txt", X)  # by default, delimited by a space

In [155]:
%cat square.txt

0.000000000000000000e+00 0.000000000000000000e+00
1.000000000000000000e+00 1.000000000000000000e+00
2.000000000000000000e+00 4.000000000000000000e+00
3.000000000000000000e+00 9.000000000000000000e+00
4.000000000000000000e+00 1.600000000000000000e+01


Another common format is *CSV*, comma-separated value.

In [156]:
np.savetxt("square.csv", X, delimiter=",", fmt="%1d, %.5f")
%ls s*

square.csv  square.txt


In [157]:
%cat square.csv

0, 0.00000
1, 1.00000
2, 4.00000
3, 9.00000
4, 16.00000


In [158]:
Y = np.loadtxt("square.txt")
Y

array([[ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

In [159]:
Y = np.loadtxt("square.csv", delimiter=",")
Y

array([[ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

## Getting help
Python offers several ways of getting help.

In [160]:
help()

Welcome to Python 3.14's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.14/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

You can use the following keyboard shortcuts at the main interpreter prompt.
F1: enter interactive help, F2: enter history browsing mode, F3: enter paste
mode (press again to exit).

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can ty

In [161]:
help(np.savetxt)

Help on method descriptor savetxt in module numpy:

savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None
)
    Save an array to a text file.

    Parameters
    ----------
    fname : filename, file handle or pathlib.Path
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:

        * a single specifier, ``fmt='%.4e'``, resulting in numbers formatted
          like ``' (%s+%sj)' % (fmt, fmt)``
        * a full string specifying every real and imag

In Jupyter notebook, you can use `?` for quick help.

In [168]:
np.*txt?

np.genfromtxt
np.loadtxt
np.savetxt

In [163]:
np.loadtxt?

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding=None,
    max_rows=None,
    *,
    quotechar=None,
    like=None,
)
Docstring:
Load data from a text file.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
    that generators must return bytes or strings. The strings
    in a list or produced by a generator are treated as lines.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or se

In [164]:
np.loadtxt??

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding=None,
    max_rows=None,
    *,
    quotechar=None,
    like=None,
)
Docstring:
Load data from a text file.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
    that generators must return bytes or strings. The strings
    in a list or produced by a generator are treated as lines.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or se

You can use 'Help' menu to jump to a variety of documentations.

## Installing a new package
A python environment is usually set up with multiple *packages*, such as numpy.  
You can check the currently installed packages by `pip list`, or `conda list` command if you installed Anaconda.

In [165]:
!pip list

Package                 Version
----------------------- -----------
asttokens               3.0.1
comm                    0.2.3
contourpy               1.3.3
cycler                  0.12.1
debugpy                 1.8.20
decorator               5.2.1
executing               2.2.1
fonttools               4.62.0
ipykernel               7.2.0
ipympl                  0.10.0
ipython                 9.11.0
ipython_pygments_lexers 1.1.1
ipywidgets              8.1.8
jedi                    0.19.2
joblib                  1.5.3
jupyter_client          8.8.0
jupyter_core            5.9.1
jupyterlab_widgets      3.0.16
kiwisolver              1.5.0
matplotlib              3.10.8
matplotlib-inline       0.2.1
nest-asyncio            1.6.0
numpy                   2.4.3
packaging               26.0
parso                   0.8.6
pexpect                 4.9.0
pillow                  12.1.1
pip                     26.0.1
platformdirs            4.9.4
prompt_toolkit          3.0.52
psutil                

If you wand to install a new package, you can use `pip install` or `conda install` command, or by Anaconda Navigator.

For example, if you have not installed `scikit-learn`, which we will use later, you can install that from your console by

```$ pip install scikit-learn```  
or  
```$ conda install scikit-learn```  
from your console.

`!pip` or `!conda` may not work if y/n input is required.