# 1. Introduction to Python: Exercise

Name: Carlos P.

In [5]:
import numpy as np

##  Lists and loops
Create the following lists, possibly in multiple ways.

1) odd positive integers below 20.

In [2]:
odd = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [3]:
odd = [n for n in range(1, 20) if n % 2 == 1]
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


2) sums from 1 to n, for up to n=10.

In [ ]:
sums = []
for i in range(1, 11):
    n = 0
    while i > 0:
        n += i
        i -= 1
    sums.append(n)

print(sums)

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]


3) prime numbers below n=20.

In [3]:
primes = []
for n in range(2, 21):
    dividers = 0
    for d in range(2, n):
        if n % d == 0:
            dividers += 1
    if dividers == 0:
        primes.append(n)
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19]


4) n=10 random numbers between 0 and k=5.  
(use np.random.randint())

In [ ]:
np.random.randint?

In [7]:
n = np.random.randint(0, 5, 10)
print(n)

[3 2 4 2 1 4 3 0 4 2]


5) from two lists of the same length, make a list with the larger of the items at the same position.

In [16]:
a = np.random.randint(10, size=5)
b = np.random.randint(10, size=5)
c = []
for i in range(5):
    if a[i] > b[i]:
        c.append(int(a[i]))
    else:
        c.append(int(b[i]))
print(a)
print(b)
print(c)


[2 2 1 4 5]
[2 1 4 8 3]
[2, 2, 4, 8, 5]


6) from a random list with 7 items, find the median 

In [ ]:
np.sort?

In [29]:
a = np.random.randint(0, 10, 7)
a_s = np.sort(a)
print(a_s)
print(a_s[3])

[0 5 5 6 6 7 8]
6


## Arrays and matrices

1) an m-by-n matrix with random integers from 0 to k.

In [31]:
# for example
m=3
n=4
k=10
A = np.random.randint(0, k, (m, n))
print(A)

[[1 5 1 8]
 [0 0 9 9]
 [6 9 9 4]]


2) from a matrix, make a sub matrix of items in odd rows and even columns.

3) make a m-by-n matrix with (i,j) component as i/j.

4) for a n-by-n matrix $A$, compute the k-th power $A^k$.